# Generated by Django 3.1.7 on 2021-06-21 11:16

import appboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'processes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('objective', models.CharField(max_length=250)),
                ('locality', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1', models.CharField(max_length=128)),
                ('id_2', models.CharField(blank=True, max_length=128, null=True)),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to=appboard.models.get_process_file_uploader_path)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_files', to='appboard.process')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='appboard.project'),
        ),
        migrations.CreateModel(
            name='MemberInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=True)),
                ('is_biller', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_invitations', to='appboard.project')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=True)),
                ('is_biller', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='appboard.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
