# Generated by Django 3.1.7 on 2021-06-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processfile',
            name='id_1',
        ),
        migrations.RemoveField(
            model_name='processfile',
            name='id_2',
        ),
        migrations.AddField(
            model_name='processfile',
            name='expected_filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='processfile',
            name='other_id_1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='processfile',
            name='stage_action_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='processfile',
            name='stage_name',
            field=models.CharField(default='load_data', max_length=128),
            preserve_default=False,
        ),
    ]
